-- 코드를 입력하세요
SELECT fo.PRODUCT_ID, fp.PRODUCT_NAME, fp.PRICE * fo.AMOUNT as TOTAL_SALES
FROM (
    SELECT PRODUCT_ID, SUM(AMOUNT) as AMOUNT
    FROM FOOD_ORDER
    WHERE DATE_FORMAT(PRODUCE_DATE, "%Y-%m") = "2022-05"
    GROUP BY PRODUCT_ID
) as fo
JOIN FOOD_PRODUCT as fp
ON fo.PRODUCT_ID = fp.PRODUCT_ID
ORDER BY TOTAL_SALES desc, fo.PRODUCT_ID;